site_name: tmxer
pages:
  - [index.md, Home]
  - [user-guide.md, User Documentation]
  - [dev-guide.md, Developer Documentation]
  - [reference.md, Reference]
  - [changelog.md, Changelog]
theme: readthedocs
